# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instagram_profile_relation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instagram_profile_relation.proto',
  package='instagram.model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n instagram_profile_relation.proto\x12\x0finstagram.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n\x14InstagramRelationDTO\x12\x15\n\rfrom_username\x18\x01 \x01(\t\x12\x13\n\x0bto_username\x18\x02 \x01(\t\x12\x15\n\rrelation_type\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INSTAGRAMRELATIONDTO = _descriptor.Descriptor(
  name='InstagramRelationDTO',
  full_name='instagram.model.InstagramRelationDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_username', full_name='instagram.model.InstagramRelationDTO.from_username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_username', full_name='instagram.model.InstagramRelationDTO.to_username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relation_type', full_name='instagram.model.InstagramRelationDTO.relation_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='instagram.model.InstagramRelationDTO.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=224,
)

_INSTAGRAMRELATIONDTO.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['InstagramRelationDTO'] = _INSTAGRAMRELATIONDTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstagramRelationDTO = _reflection.GeneratedProtocolMessageType('InstagramRelationDTO', (_message.Message,), {
  'DESCRIPTOR' : _INSTAGRAMRELATIONDTO,
  '__module__' : 'instagram_profile_relation_pb2'
  # @@protoc_insertion_point(class_scope:instagram.model.InstagramRelationDTO)
  })
_sym_db.RegisterMessage(InstagramRelationDTO)


# @@protoc_insertion_point(module_scope)
