# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instagram_profile_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instagram_profile_history.proto',
  package='instagram.model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1finstagram_profile_history.proto\x12\x0finstagram.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n\x1aInstagramProfileHistoryDTO\x12R\n\x0cprofile_spec\x18\x01 \x03(\x0b\x32<.instagram.model.InstagramProfileHistoryDTO.ProfileSpecEntry\x12\x17\n\x0ftotal_followers\x18\x02 \x01(\r\x12\x17\n\x0ftotal_followees\x18\x03 \x01(\r\x12\x13\n\x0bmedia_count\x18\x04 \x01(\r\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x32\n\x10ProfileSpecEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY = _descriptor.Descriptor(
  name='ProfileSpecEntry',
  full_name='instagram.model.InstagramProfileHistoryDTO.ProfileSpecEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='instagram.model.InstagramProfileHistoryDTO.ProfileSpecEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='instagram.model.InstagramProfileHistoryDTO.ProfileSpecEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=369,
)

_INSTAGRAMPROFILEHISTORYDTO = _descriptor.Descriptor(
  name='InstagramProfileHistoryDTO',
  full_name='instagram.model.InstagramProfileHistoryDTO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_spec', full_name='instagram.model.InstagramProfileHistoryDTO.profile_spec', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_followers', full_name='instagram.model.InstagramProfileHistoryDTO.total_followers', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_followees', full_name='instagram.model.InstagramProfileHistoryDTO.total_followees', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='media_count', full_name='instagram.model.InstagramProfileHistoryDTO.media_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='instagram.model.InstagramProfileHistoryDTO.updated_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=369,
)

_INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY.containing_type = _INSTAGRAMPROFILEHISTORYDTO
_INSTAGRAMPROFILEHISTORYDTO.fields_by_name['profile_spec'].message_type = _INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY
_INSTAGRAMPROFILEHISTORYDTO.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['InstagramProfileHistoryDTO'] = _INSTAGRAMPROFILEHISTORYDTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstagramProfileHistoryDTO = _reflection.GeneratedProtocolMessageType('InstagramProfileHistoryDTO', (_message.Message,), {

  'ProfileSpecEntry' : _reflection.GeneratedProtocolMessageType('ProfileSpecEntry', (_message.Message,), {
    'DESCRIPTOR' : _INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY,
    '__module__' : 'instagram_profile_history_pb2'
    # @@protoc_insertion_point(class_scope:instagram.model.InstagramProfileHistoryDTO.ProfileSpecEntry)
    })
  ,
  'DESCRIPTOR' : _INSTAGRAMPROFILEHISTORYDTO,
  '__module__' : 'instagram_profile_history_pb2'
  # @@protoc_insertion_point(class_scope:instagram.model.InstagramProfileHistoryDTO)
  })
_sym_db.RegisterMessage(InstagramProfileHistoryDTO)
_sym_db.RegisterMessage(InstagramProfileHistoryDTO.ProfileSpecEntry)


_INSTAGRAMPROFILEHISTORYDTO_PROFILESPECENTRY._options = None
# @@protoc_insertion_point(module_scope)
